######################################################################
# RIALTO
######################################################################
#
# Rialto provides a solution to implement the AV (audio and video) pipelines of containerised native applications
# and browsers without exposing hardware-specific handles and critical system resources inside the application containers

SRCREV:pn-rialto ?= "v0.11.0"
SRCREV:pn-rialto-ocdm ?= "v0.9.0"
SRCREV:pn-rialto-gstreamer ?= "v0.10.0"
