# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""


BBLAYERS ?= " \
  ${TOPDIR}/../meta \
  ${TOPDIR}/../meta-poky \
  ${TOPDIR}/../meta-yocto-bsp \
  ${TOPDIR}/../meta-openembedded/meta-oe \
  ${TOPDIR}/../meta-openembedded/meta-python \
  ${TOPDIR}/../meta-openembedded/meta-filesystems \
  ${TOPDIR}/../meta-openembedded/meta-networking \
  ${TOPDIR}/../meta-openembedded/meta-multimedia \
  ${TOPDIR}/../meta-virtualization \
  ${TOPDIR}/../meta-raspberrypi \
  ${TOPDIR}/../meta-python2 \
  ${TOPDIR}/../meta-dac-sdk \
"

BBLAYERS += "${@'${TOPDIR}/../meta-clang' if os.path.isfile('${TOPDIR}/../meta-clang/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-cmf' if os.path.isfile('${TOPDIR}/../meta-cmf/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-dac-image' if os.path.isfile('${TOPDIR}/../meta-dac-image/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-qt5' if os.path.isfile('${TOPDIR}/../meta-qt5/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-rdk' if os.path.isfile('${TOPDIR}/../meta-rdk/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-rdk-ext' if os.path.isfile('${TOPDIR}/../meta-rdk-ext/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-rdk-cobalt' if os.path.isfile('${TOPDIR}/../meta-rdk-cobalt/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-rdk-flutter' if os.path.isfile('${TOPDIR}/../meta-rdk-flutter/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-rdk-video' if os.path.isfile('${TOPDIR}/../meta-rdk-video/conf/layer.conf') else ''}"
BBLAYERS += "${@'${TOPDIR}/../meta-webkit' if os.path.isfile('${TOPDIR}/../meta-webkit/conf/layer.conf') else ''}"

BBLAYERS += "${@' \
  ${TOPDIR}/../rdke/common/meta-rdk-oss-reference \
  ${TOPDIR}/../rdke/middleware/generic/meta-middleware-generic-support \
  ${TOPDIR}/../rdke/middleware/generic/meta-rdk \
  ${TOPDIR}/../rdke/middleware/generic/meta-rdk-video \
  ${TOPDIR}/../rdke/application/meta-application-rdke-dev \
' if os.path.isdir('${TOPDIR}/../rdke') else ''}"
