BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-dac-image-cobalt"
BBFILE_PATTERN_meta-dac-image-cobalt = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-dac-image-cobalt = "100"

LAYERDEPENDS_meta-dac-image-cobalt = "meta-dac"
LAYERSERIES_COMPAT_meta-dac-image-cobalt = "kirkstone"

# a newer version is needed to compile rpcserver
PREFERRED_VERSION_jsoncpp = "1.9.5"

PREFERRED_PROVIDER_virtual/cobalt-evergreen = "${@bb.utils.contains('DISTRO_FEATURES', 'no_pixel_buffer_surfaces', 'cobalt-evergreen-src', 'cobalt-evergreen-pbt', d)}"
