BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-dac-image-wpe"
BBFILE_PATTERN_meta-dac-image-wpe = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-dac-image-wpe = "100"

LAYERDEPENDS_meta-dac-image-wpe = "meta-dac"
LAYERSERIES_COMPAT_meta-dac-image-wpe = "kirkstone dunfell"

OCI_IMAGE_BACKEND = "sloci-image"

BBPATH .= ":${LAYERDIR}/meta-webkit"
BBFILES += "${LAYERDIR}/meta-webkit/recipes-browser/cog/cog_0.16.1.bb"
